<a href="https://colab.research.google.com/github/FazleRabbbiferdaus172/Tensorflow/blob/master/TensorFlow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing tensorflow**


In [0]:
%tensorflow_version 2.x #this is not required in other txt editor..only in notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x #this is not required in other txt editor..only in notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [0]:
import tensorflow as tf #import the tensorflow module
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


varables of tensors with different data types

In [0]:
string = tf.Variable("this is a string",tf.string) #scalar
number = tf.Variable(71,tf.int32) #scalar
floating = tf.Variable(19.71,tf.float64) #scalar
rank1_tensor = tf.Variable(["this","is","a","test"],tf.string) 
rank2_tensor = tf.Variable([["fazle","one"],["rabbi","two"],["ferdaus","three"]],tf.string)


#Rank
rank means the dimesion of tensor variable

In [0]:
#tf.rank(rank1_tensor)
#tf.rank(rank2_tensor)
#tf.rank(number) #scalar tensors dont have ranks

#Shape
Shape indicates how many elements are there in  a tensor

In [0]:
rank1_tensor.shape

TensorShape([4])

#Changing Shape

In [0]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1])

t = tf.zeros([5,5,5,5])
t = tf.reshape(t, [125, -1])

In [0]:
print(tensor1)
print(tensor2)
print(tensor3)
print(t)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [

#Types of tensors
1. Variables
2. Constant
3. Placeholder
4. SparseTensor

With the execption of variable all of these tensors are immuttable(there values may not change)

#Evaluating tensor


In [0]:
with tf.compat.v1.Session() as sess:
    tensor1.eval()